---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Create v2.1.2 upgrade directory.
      file:
          path: ~/upgrade_v212
          state: directory

    - name: Install Crypto.org v2.1.2 Chain binaries from official Github.
      shell: "curl -LOJ https://github.com/crypto-org-chain/chain-main/releases/download/v2.1.2/chain-main_2.1.2_Linux_x86_64.tar.gz"
      become: yes
      args:
        chdir: ~/upgrade_v212

    - name: Extract chain-main v2.1.2 gzip compressed data.
      shell: "tar -zxvf chain-main_2.1.2_Linux_x86_64.tar.gz"
      become: yes
      args:
        chdir: ~/upgrade_v212

    - name: Verify chain-maind version is 2.1.2 (through shell).
      shell: "./bin/chain-maind version"
      become: yes
      args:
        chdir: ~/upgrade_v212

     - name: Transfer the upgrade_v212.sh script from local to remote
       copy: src=~/upgrade_v212.sh dest=~/upgrade_v212 mode=0777

     - name: Execute the upgrade_v212.sh script.
       command: sh ~/upgrade_v212/upgrade_v212.sh

      - name:  Start the node and output logging to node.log.
        shell: "nohup ./bin/chain-maind start > node.log 2>&1 &"
        become: yes
        args:
           chdir: ~/upgrade_v212
